### ISSUE TITLE
Mega-Mega-Task: Improve COINSTAC documentation and wiki

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1396]
# Sub-tasks
- [ ] Create a foundation for others to contribute to the wiki easily. 
- [ ] Compile and organize all documentation to new location.

## Documentation mega-tasks:

- [ ] https://github.com/trendscenter/coinstac/issues/1398 - Documentation for End Users
- [ ] https://github.com/trendscenter/coinstac/issues/1399 - Documentation for developers

## Key sub-tasks:

- [ ] https://github.com/trendscenter/coinstac/issues/1431 - Create process for publishing documentation to Github wiki(s) or Pages
- [ ] https://github.com/trendscenter/coinstac/issues/1417 - Stub out a Dev Documentation section in Github pages via Docusaurus
- [ ] https://github.com/trendscenter/coinstac/issues/1418 - Stub out a User Documentation section in the wiki
- [ ] https://github.com/trendscenter/coinstac/issues/1334 - Document best practices and design patterns for computation authors

## Related tasks:
- [ ] https://github.com/trendscenter/coinstac/issues/1427 - Build out a plan to address important user experience improvements
- [ ] https://github.com/trendscenter/coinstac/issues/1329 - DevOps Future State Architecture
