### ISSUE TITLE
Mega-Task: Documentation for developers

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1399]
# Sub-tasks:
## Higher Priority (by end of 2022)
- [x] Onboarding: https://github.com/trendscenter/coinstac/issues/1417

## Lower Priority (early 2023)

- [ ] Automate COINSTAC setup process for new developers - https://github.com/trendscenter/coinstac/issues/1397
- [ ] Requirements analysis 
- [ ] Document current functionality
- [ ] Code structure / file / file group descriptions: as a developer I know where to start and how to contribute
- [ ] How components/services interact and communication
- [ ] Architecture / system design descriptions - see "architecture" label in github issues
- [ ] Local environment setup documentation
- [ ] Cloud deployment documentation for the back-end
- [ ] GSU server deployment documentation for clients
- [ ] How back-end services communicate to each other
- [ ] Update https://github.com/trendscenter/coinstac/blob/master/SETUP.md: to operate on production you dont need npm run start but need npm run watch in coinstac-ui but also need to run npm run switch:prod in the top level directory

**Comment by praeducer** [comment]
Really rough notes from when @dylanmartin, Caleb, and I first setup COINSTAC on our local machines: 
[Improve_documentation_and_setup_process_in_COINSTAC_repo.pdf](https://github.com/trendscenter/coinstac/files/9213141/Improve_documentation_and_setup_process_in_COINSTAC_repo.pdf)
![Image](https://user-images.githubusercontent.com/4081511/181607024-841822cf-415d-4de0-8928-fda3f2ceb4ae.png)
![Image](https://user-images.githubusercontent.com/4081511/181607025-9a72d3d9-6cfd-435d-9bf6-4389f9b72fda.png)
![Image](https://user-images.githubusercontent.com/4081511/181607023-95174536-3f67-400a-9918-c3d4bc36c952.png)
![Image](https://user-images.githubusercontent.com/4081511/181607026-bab0f3bb-7a8c-4ff1-8f2f-78e2636e1e62.png)

**Comment by praeducer** [comment]
Related tasks:
#1397

**Comment by BluntBSE** [comment]
Here I am documenting issues encountered in my attempt to install and run Coinstac per the instructions provided in Setup.md.

1. Was not able to install windows-build-tools due to a hang while installing python 2.7. Per recommendation about this being deprecated (npm has build tools now), I just installed lerna globally, which allowed me to proceed.

2. Got to npm run start, and ran into issues with coinstac-api-server & sleep. Attempted to in
stall packages in coinstac-api-server again. Continued to get issues related to searching for a missing 'compat' module. 
![Compat](https://user-images.githubusercontent.com/31498420/187529864-af0ae723-0c6a-4f7a-99d3-04798f8cca2a.jpg)

**Comment by dylanmartin** [comment]
SETUP.md was linking to the MRN repository. I just updated the documentation and pushed.
https://github.com/trendscenter/coinstac/commit/7441656ff3a742db92e7c70108eb0f49c5fdb83a

**Comment by BluntBSE** [comment]
@praeducer  @dylanmartin  - I managed to get the Electron Application running, though I now receive a "connection refused" error, in the screenshot attached. Looks like an error with webpack or the local server (started by Electron?) (bundle.js not found). I haven't used Electron so I don't understand the context here of what might need fixing. Mosquito appears to be running without issue.

Question about the installation instructions: is "windows-build-tools" still necessary? The instructions use node, and WBT itself suggests it's deprecated if you have node installed. I had trouble get windows-build-tools to even install (and many other people do too), but was able to proceed with installation just by installing lerna. I am using Windows 11.

Would it be appropriate to update the instructions to use lerna? If so, may I try my hand at making a pull request? I'd love to understand what else windows-build-tools is used for, and if my OS is why I got away with using lerna alone.

![ConnectRefused](https://user-images.githubusercontent.com/31498420/187993312-cee60b79-5afd-43a2-9baa-eaa35679681b.jpg)

**Comment by BluntBSE** [comment]
FWIW bundle.js exists at "C:\Users\ramne\Desktop\COINSTAC1\coinstac\packages\coinstac-ui\build", which I assume is what electron is looking at based on the yaml.

**Comment by praeducer** [comment]
@BluntBSE looks like the team is considering giving you write access for pull requests. We'll report back!

**Comment by dylanmartin** [comment]
@BluntBSE did you run `npm run start` from your console before launching the debug process?

**Comment by BluntBSE** [comment]
@dylanmartin  I did indeed. The only deviation from the instructions was that fact that I did not install windows-build-tools, but only lerna.

**Comment by BluntBSE** [comment]
Update to the above: My connection refused errors were tied to an obscure NPM installation issue on my end. Dylan and I have discussed some updates to make to the installation process, however, which I will document in a pull request.

**Comment by dylanmartin** [comment]
@praeducer @rssk  Here are some questions we should answer:
Should we move SETUP.md out of the code repo and into the wiki? If so, should all readmes be pulled out into the wiki? Should any documentation live in the code repo?

https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis


It looks like the github docs suggest having both READMEs in the code repos as well as wiki pages for longer form content
![Image](https://user-images.githubusercontent.com/7193853/189716903-c701f07d-9498-4b1a-9571-0b9493bb6613.png)


By default, outside contributors cannot edit wiki content - a weakness compared to documentation in the repo - but it looks like that can be changed.
![Image](https://user-images.githubusercontent.com/7193853/189717500-5b7ae2d2-7508-4eb0-a9e5-7588395719ee.png)

**Comment by dylanmartin** [comment]
@rssk @praeducer What are the next areas we should focus on with documentation?
