### ISSUE TITLE
Publish an AMI for COINSTAC in AWS Marketplace through Hyperbloom Partnership

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1467]
**Business value**: 
- We need to make clear steps towards commercialization to better qualify for SBIR grants. We also often need to spin these up for researchers, computations authors, and devs doing QA work. It would be good to have something public with instructions on how someone can spin up a virtualized instance of the client UI in their own AWS account.
- Increasing adoption. Easy to access for any users of AWS, including ourselves. 
- Providing a better user experience. 

**Sub-Tasks**:

- [x] Learn more about COINSTAC and how the system design
- [x] Get it working locally first
- [x] Gather more requirements, ask more questions
- [x] Get access and permissions to Hyperbloom's VPC
- [x] Ask @dylanmartin to share the AMI that is already in the TReNDS Center AWS environment and how he would want to improve it. 
- [x] Decide on AMI and its hardware requirements that will make our users happy (make sure it provides a good user experience, like speed, while balancing costs). Use this to recommend this in the marketplace page. 
- [x] Present AMI choice here in this task for approval
- [x] Preconfigure/preinstall COINSTAC on the AMI
- [x] Address security vulnerabilities. This involves public keys and passwords are locked down (e.g. keys used to ssh into the instance). 
- [x] Document everything you did to get here. Write down the steps to do this again and publish them in the COINSTAC wiki.
- [x] **Publish the AMI as an AWS Marketplace solution.** This includes things like writing the setup documentation and figuring licensing requirements (@praeducer can own documentation and licensing). 
- [x] **Spin up a QAT environment for COINSTAC in Hyperbloom's AWS VPC** as a way to test the marketplace solution. 
- [x] Cost optimize / clean up Hyperbloom's AWS environment.
- [x] @Nonzzo Can give @praeducer a demo! Then we can give a demo to COINSTAC team.

Potential Future Work:
- [ ] Write an IaC / Terraform solution for automating the spinning up of this kind of a development server.
- [ ] Helping the tech lead of COINSTAC with containerizations issues.

**Comment by praeducer** [comment]
.

**Comment by praeducer** [comment]
@dylanmartin and @Nonzzo Do these sub-tasks or goals need to be adjusted for Nonso? It would be good for Nonso to get a Pull Request accepted or something in the AWS Marketplace by October 7th so Hyperbloom can compensate him.

**Comment by praeducer** [comment]
After thinking about it, the main business outcome I want see is that we have a COINSTAC AMI preconfigured with the full stack application ready to run up in the AWS Marketplace tagged as a Life Sciences solution.
A secondary goal is that we support multiple instances types such as:
1. Cheap / cost optimized / min hardware reqs
2. GPU powered instance
3. Super computer / HPC

**Comment by praeducer** [comment]
I believe this is my goal: https://docs.aws.amazon.com/marketplace/latest/userguide/ami-single-ami-products.html

**Comment by praeducer** [comment]
Here is a concrete example: https://aws.amazon.com/marketplace/pp/prodview-ne5rvajz7iywq?sr=0-1&ref_=beagle&applicationId=AWSMPContessa

Instead thought, we want something like: "TReNDS Center COINSTAC Open Source for Ubuntu 18.04 with support by Hyperbloom"

**Comment by praeducer** [comment]
Maybe in the next iteration, we need to also place what we can in Docker. @rssk Can you provide what you would like to see?

**Comment by praeducer** [comment]
Another good example: https://aws.amazon.com/marketplace/pp/prodview-lk4iosjt3ppio?ref_=awsmp_sol_hlth_mimg_pp_unif&trk=awsmp_sol_hlth_mimg_pp_unif

**Comment by praeducer** [comment]
@Nonzzo would like one more week to get this done. 

The goal is to get the UI published as a Linux AMI in the AWS Marketplace.

**Comment by praeducer** [comment]
Still need to benchmark and experiment with the hardware requirements to choose the optimal AMI to suggest. In the marketplace, need to configure marketplace settings. Just find one that is good enough, @Nonzzo.

**Comment by praeducer** [comment]
@Nonzzo consider putting in a support ticket to AWS for the SSH key issue. Make sure they know we are a partner and this is a security issue. That should get it the right attention.

**Comment by praeducer** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/get-aws-technical-support/

**Comment by praeducer** [comment]
@Nonzzo our lead front end dev, @pixelsaurus, would love a demo when you're ready!

**Comment by praeducer** [comment]
Note: This is planned to be offered for free. Paul will talk to GSU legal team when he can make time.

**Comment by dylanmartin** [comment]
Here's a possible stumbling block in submitting an AMI to be scanned by AWS:
Depending on which base image your AMI is using, the default username can be different. though the documentation recommends using `ec2-user`, Ubuntu AMIs use `ubuntu`
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/TroubleshootingInstancesConnecting.html

Make sure to manually change the username to fit when submitting the AMI for scan.
![image (24)](https://user-images.githubusercontent.com/7193853/199784702-8d26b3e0-9200-4a68-850c-302b04c1ccb0.png)

**Comment by Nonzzo** [comment]
Yes. Its the issue. thanks

**Comment by Nonzzo** [comment]
[Setting up the coinstac AMI and Using it.pdf](https://github.com/trendscenter/coinstac/files/9946944/Setting.up.the.coinstac.AMI.and.Using.it.pdf)
