### ISSUE TITLE
Computation test coverage

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1941]
## Task Description
Make tests for the following computations, look at their github repos for test data:

- [x]  coinstacteam/msr-fsl  
- [ ]  coinstacteam/coinstac-dsbm 
- [x]  coinstacteam/coinstac-msr-csv
- [x]  coinstacteam/regression-csv
- [ ]  coinstacteam/coinstac-combatdc
- [x]  coinstacteam/coinstac-dpsvm-csv
- [ ]  coinstacteam/dpsvm
- [ ]  coinstacteam/coinstac-dist-meshnet
- [x]  coinstacteam/coinstac-ssr-csv
- [x]  coinstacteam/regression-fsl
- [x]  coinstacteam/regression-vbm
